list:
  path: /
  controller: App\Controller\MainController:ListAction

create:
  path: /create
  controller: App\Controller\MainController:CreateAction

update:
  path: /update/{id}
  controller: App\Controller\MainController:UpdateAction

delete:
  path: /delete/{id}
  controller: App\Controller\MainController:DeleteAction