list:
  path: /
  controller: App\Controller\MainController:ListAction

create:
  path: /create
  controller: App\Controller\MainController:CreateAction

update:
  path: /update
  controller: App\Controller\MainController:Update

delete:
  path: /delete
  controller: App\Controller\MainController:Delete